# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: namemcplus
open_collective: # Replace with a single Open Collective username
ko_fi: namemcplus
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom:  ["bitcoin:bc1qjga8e0xdeaea9jnhk3988l5txk2v4kqyxastdp" ,"XMR--44rFyaA1fMTVsMnyjmCCyd4gdn4h4wtRtdESb8hcvaNnBDtV1REsWs6AM2Er2o4Tk1gP3KoMb6nqpGLRyxNHs38gBRdUSkr"]
